run:
  tests: true
  go: ""
  modules-download-mode: "readonly"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - stylecheck
    - govet
    - unused

issues:
  include:
    # Include Close() errcheck https://golangci-lint.run/usage/false-positives/#exc0001
    - EXC0001
  exclude:
    # Exclude ALL_CAPS for constants check
    - ST1003
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0
